spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/micro-realm-by-me
        registration:
          spring-gateway-client:
            client-name: micro-auth-by-me
            client-id: micro-auth-by-me
            client-secret: 1pGG6C5GIwujJ8jL8cZ0SRzM89uobpfH
            authorization-grant-type: authorization_code
            scope: openid
            provider: keycloak
            redirect-uri: http://localhost:9191/login/oauth2/code/spring-gateway-client
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      default-filters: TokenRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackUri: forward:/fallback/productsServiceFallBack
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackUri: forward:/fallback/orderServiceFallBack
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true

resilience4j:
  circuitbreaker:
    instances:
      CircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

management:
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always